---
deployment:
  tasks:
    - export SOURCE=/home/mudamudi/public.html
    - export TARGET=/home/mudamudi/public_html

    - /bin/cp -a $SOURCE/*.html $TARGET/
    - if [ -f "$SOURCE/style.css" ]; then /bin/cp -a "$SOURCE/style.css" "$TARGET/"; fi
    - if [ -f "$SOURCE/script.js" ]; then /bin/cp -a "$SOURCE/script.js" "$TARGET/"; fi
    - if [ -d "$SOURCE/images" ]; then /bin/cp -a "$SOURCE/images" "$TARGET/"; fi
    - if [ -d "$SOURCE/gambar&animasi" ]; then /bin/cp -a "$SOURCE/gambar&animasi" "$TARGET/"; fi

    - /bin/mkdir -p $TARGET/billiard
    - /bin/cp -a $SOURCE/billiard/index.html $TARGET/billiard/
    - /bin/cp -a $SOURCE/billiard/lobby.html $TARGET/billiard/
    - /bin/cp -a $SOURCE/billiard/room.html $TARGET/billiard/
    - /bin/cp -a $SOURCE/billiard/game.html $TARGET/billiard/
    - /bin/cp -a $SOURCE/billiard/assets $TARGET/billiard/

    - /bin/mkdir -p $TARGET/billiard/api
    - /bin/cp -a $SOURCE/billiard/api/*.php $TARGET/billiard/api/
